schema_version = "1.0.0"

id = "pipe_sculpt"
version = "0.16.0"
name = "PipeSculpt"
tagline = "Pie-menus and workflow pipeline for character and face sculpting"
maintainer = "Piper"
type = "add-on"

blender_version_min = "5.0.0"

license = ["SPDX:GPL-3.0-or-later"]

tags = ["Sculpt", "Mesh"]
